health:
    path: /health
    methods: [ "GET" ]
    controller: TableDragon\Infrastructure\Controller\HealthController

players_show:
    path: /players/{player_id}
    controller: TableDragon\Infrastructure\Controller\Player\PlayerController::show
    methods: GET
    requirements:
        player_id: '.+'

players_index:
    path: /players/
    controller: TableDragon\Infrastructure\Controller\Player\PlayerController::index
    methods: GET

players_create:
    path: /players/
    controller: TableDragon\Infrastructure\Controller\Player\PlayerController::create
    methods: POST

categories_index:
    path: /categories/
    controller: TableDragon\Infrastructure\Controller\Category\CategoryController::index
    methods: GET